//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class User : object
    {
        
        private string NameField;
        
        private int UserIdField;
        
        private string emailField;
        
        private string surnameField;
        
        private string userTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Student : object
    {
        
        private string Stu_emailField;
        
        private string Stu_nameField;
        
        private string Stu_passwordField;
        
        private string Stu_surnameField;
        
        private System.Nullable<char> Stu_typeField;
        
        private int Student_numField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stu_email
        {
            get
            {
                return this.Stu_emailField;
            }
            set
            {
                this.Stu_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stu_name
        {
            get
            {
                return this.Stu_nameField;
            }
            set
            {
                this.Stu_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stu_password
        {
            get
            {
                return this.Stu_passwordField;
            }
            set
            {
                this.Stu_passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stu_surname
        {
            get
            {
                return this.Stu_surnameField;
            }
            set
            {
                this.Stu_surnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Stu_type
        {
            get
            {
                return this.Stu_typeField;
            }
            set
            {
                this.Stu_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_num
        {
            get
            {
                return this.Student_numField;
            }
            set
            {
                this.Student_numField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prescribe_Exercise", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Prescribe_Exercise : object
    {
        
        private int Couns_idField;
        
        private System.DateTime Date_prescribedField;
        
        private int Ex_idField;
        
        private int IDField;
        
        private System.Nullable<int> IsLatestCompletedField;
        
        private System.Nullable<int> Student_NumField;
        
        private System.Nullable<int> isprescribedField;
        
        private System.Nullable<int> num_completionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Couns_id
        {
            get
            {
                return this.Couns_idField;
            }
            set
            {
                this.Couns_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_prescribed
        {
            get
            {
                return this.Date_prescribedField;
            }
            set
            {
                this.Date_prescribedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ex_id
        {
            get
            {
                return this.Ex_idField;
            }
            set
            {
                this.Ex_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsLatestCompleted
        {
            get
            {
                return this.IsLatestCompletedField;
            }
            set
            {
                this.IsLatestCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Student_Num
        {
            get
            {
                return this.Student_NumField;
            }
            set
            {
                this.Student_NumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isprescribed
        {
            get
            {
                return this.isprescribedField;
            }
            set
            {
                this.isprescribedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> num_completion
        {
            get
            {
                return this.num_completionField;
            }
            set
            {
                this.num_completionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Counsellor", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Counsellor : object
    {
        
        private System.Nullable<int> Admin_idField;
        
        private string Couns_SurnameField;
        
        private string Couns_emailField;
        
        private int Couns_idField;
        
        private string Couns_nameField;
        
        private string Couns_passwordField;
        
        private int NumStudentsLinkedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Admin_id
        {
            get
            {
                return this.Admin_idField;
            }
            set
            {
                this.Admin_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Couns_Surname
        {
            get
            {
                return this.Couns_SurnameField;
            }
            set
            {
                this.Couns_SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Couns_email
        {
            get
            {
                return this.Couns_emailField;
            }
            set
            {
                this.Couns_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Couns_id
        {
            get
            {
                return this.Couns_idField;
            }
            set
            {
                this.Couns_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Couns_name
        {
            get
            {
                return this.Couns_nameField;
            }
            set
            {
                this.Couns_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Couns_password
        {
            get
            {
                return this.Couns_passwordField;
            }
            set
            {
                this.Couns_passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumStudentsLinked
        {
            get
            {
                return this.NumStudentsLinkedField;
            }
            set
            {
                this.NumStudentsLinkedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Admin : object
    {
        
        private string Admin_NameField;
        
        private string Admin_emailField;
        
        private int Admin_idField;
        
        private string Admin_passwordField;
        
        private string Admin_surnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Admin_Name
        {
            get
            {
                return this.Admin_NameField;
            }
            set
            {
                this.Admin_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Admin_email
        {
            get
            {
                return this.Admin_emailField;
            }
            set
            {
                this.Admin_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Admin_id
        {
            get
            {
                return this.Admin_idField;
            }
            set
            {
                this.Admin_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Admin_password
        {
            get
            {
                return this.Admin_passwordField;
            }
            set
            {
                this.Admin_passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Admin_surname
        {
            get
            {
                return this.Admin_surnameField;
            }
            set
            {
                this.Admin_surnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exercise", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Exercise : object
    {
        
        private string EX_descriptionField;
        
        private System.Nullable<char> Ex_activeField;
        
        private int Ex_idField;
        
        private string Ex_nameField;
        
        private System.Nullable<char> Ex_statusField;
        
        private string mediaPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_description
        {
            get
            {
                return this.EX_descriptionField;
            }
            set
            {
                this.EX_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Ex_active
        {
            get
            {
                return this.Ex_activeField;
            }
            set
            {
                this.Ex_activeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ex_id
        {
            get
            {
                return this.Ex_idField;
            }
            set
            {
                this.Ex_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ex_name
        {
            get
            {
                return this.Ex_nameField;
            }
            set
            {
                this.Ex_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Ex_status
        {
            get
            {
                return this.Ex_statusField;
            }
            set
            {
                this.Ex_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mediaPath
        {
            get
            {
                return this.mediaPathField;
            }
            set
            {
                this.mediaPathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book_Consultation", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Book_Consultation : object
    {
        
        private System.Nullable<System.DateTime> Book_dateField;
        
        private int Book_numberField;
        
        private string Book_timeField;
        
        private System.Nullable<int> Couns_idField;
        
        private System.Nullable<int> Student_numField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Book_date
        {
            get
            {
                return this.Book_dateField;
            }
            set
            {
                this.Book_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Book_number
        {
            get
            {
                return this.Book_numberField;
            }
            set
            {
                this.Book_numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Book_time
        {
            get
            {
                return this.Book_timeField;
            }
            set
            {
                this.Book_timeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Couns_id
        {
            get
            {
                return this.Couns_idField;
            }
            set
            {
                this.Couns_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Student_num
        {
            get
            {
                return this.Student_numField;
            }
            set
            {
                this.Student_numField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diary", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class Diary : object
    {
        
        private System.Nullable<System.DateTime> Diary_dateField;
        
        private string Diary_descriptionField;
        
        private int Diary_idField;
        
        private string Diary_titleField;
        
        private System.Nullable<int> Student_numField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Diary_date
        {
            get
            {
                return this.Diary_dateField;
            }
            set
            {
                this.Diary_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diary_description
        {
            get
            {
                return this.Diary_descriptionField;
            }
            set
            {
                this.Diary_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Diary_id
        {
            get
            {
                return this.Diary_idField;
            }
            set
            {
                this.Diary_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diary_title
        {
            get
            {
                return this.Diary_titleField;
            }
            set
            {
                this.Diary_titleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Student_num
        {
            get
            {
                return this.Student_numField;
            }
            set
            {
                this.Student_numField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StuCounsLink", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class StuCounsLink : object
    {
        
        private int LinkIDField;
        
        private System.Nullable<int> Stu_NumField;
        
        private System.Nullable<int> couns_idField;
        
        private System.Nullable<int> islinkedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinkID
        {
            get
            {
                return this.LinkIDField;
            }
            set
            {
                this.LinkIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stu_Num
        {
            get
            {
                return this.Stu_NumField;
            }
            set
            {
                this.Stu_NumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> couns_id
        {
            get
            {
                return this.couns_idField;
            }
            set
            {
                this.couns_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> islinked
        {
            get
            {
                return this.islinkedField;
            }
            set
            {
                this.islinkedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableDateAndTime", Namespace="http://schemas.datacontract.org/2004/07/MindOverMatterService")]
    public partial class AvailableDateAndTime : object
    {
        
        private int CounsIDField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private int IDField;
        
        private string TimeField;
        
        private System.Nullable<int> isAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounsID
        {
            get
            {
                return this.CounsIDField;
            }
            set
            {
                this.CounsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isAvailable
        {
            get
            {
                return this.isAvailableField;
            }
            set
            {
                this.isAvailableField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        ServiceReference1.User loginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        System.Threading.Tasks.Task<ServiceReference1.User> loginUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginStudent", ReplyAction="http://tempuri.org/IService1/loginStudentResponse")]
        ServiceReference1.Student loginStudent(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginStudent", ReplyAction="http://tempuri.org/IService1/loginStudentResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Student> loginStudentAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/regUser", ReplyAction="http://tempuri.org/IService1/regUserResponse")]
        bool regUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/regUser", ReplyAction="http://tempuri.org/IService1/regUserResponse")]
        System.Threading.Tasks.Task<bool> regUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditStudent", ReplyAction="http://tempuri.org/IService1/EditStudentResponse")]
        bool EditStudent(int id, string name, string surname, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditStudent", ReplyAction="http://tempuri.org/IService1/EditStudentResponse")]
        System.Threading.Tasks.Task<bool> EditStudentAsync(int id, string name, string surname, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCounsellor", ReplyAction="http://tempuri.org/IService1/EditCounsellorResponse")]
        bool EditCounsellor(int id, string name, string surname, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCounsellor", ReplyAction="http://tempuri.org/IService1/EditCounsellorResponse")]
        System.Threading.Tasks.Task<bool> EditCounsellorAsync(int id, string name, string surname, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivateCounsellor", ReplyAction="http://tempuri.org/IService1/ActivateCounsellorResponse")]
        bool ActivateCounsellor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivateCounsellor", ReplyAction="http://tempuri.org/IService1/ActivateCounsellorResponse")]
        System.Threading.Tasks.Task<bool> ActivateCounsellorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivateExercise", ReplyAction="http://tempuri.org/IService1/ActivateExerciseResponse")]
        bool ActivateExercise();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivateExercise", ReplyAction="http://tempuri.org/IService1/ActivateExerciseResponse")]
        System.Threading.Tasks.Task<bool> ActivateExerciseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addExercise", ReplyAction="http://tempuri.org/IService1/addExerciseResponse")]
        bool addExercise(int id, string name, string description, char status, char active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addExercise", ReplyAction="http://tempuri.org/IService1/addExerciseResponse")]
        System.Threading.Tasks.Task<bool> addExerciseAsync(int id, string name, string description, char status, char active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditExercise", ReplyAction="http://tempuri.org/IService1/EditExerciseResponse")]
        bool EditExercise(int id, string name, string decription, char status, char active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditExercise", ReplyAction="http://tempuri.org/IService1/EditExerciseResponse")]
        System.Threading.Tasks.Task<bool> EditExerciseAsync(int id, string name, string decription, char status, char active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/prescribeExercise", ReplyAction="http://tempuri.org/IService1/prescribeExerciseResponse")]
        bool prescribeExercise(int counsID, int studentID, int exerciseID, System.DateTime dateprescribed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/prescribeExercise", ReplyAction="http://tempuri.org/IService1/prescribeExerciseResponse")]
        System.Threading.Tasks.Task<bool> prescribeExerciseAsync(int counsID, int studentID, int exerciseID, System.DateTime dateprescribed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnPrescribeExercise", ReplyAction="http://tempuri.org/IService1/UnPrescribeExerciseResponse")]
        bool UnPrescribeExercise(int counsID, int exerciseID, int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnPrescribeExercise", ReplyAction="http://tempuri.org/IService1/UnPrescribeExerciseResponse")]
        System.Threading.Tasks.Task<bool> UnPrescribeExerciseAsync(int counsID, int exerciseID, int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/exerciseCompleted", ReplyAction="http://tempuri.org/IService1/exerciseCompletedResponse")]
        bool exerciseCompleted(int counsID, int exerciseID, int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/exerciseCompleted", ReplyAction="http://tempuri.org/IService1/exerciseCompletedResponse")]
        System.Threading.Tasks.Task<bool> exerciseCompletedAsync(int counsID, int exerciseID, int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPrescribedExercises", ReplyAction="http://tempuri.org/IService1/getPrescribedExercisesResponse")]
        ServiceReference1.Prescribe_Exercise[] getPrescribedExercises(int studentNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPrescribedExercises", ReplyAction="http://tempuri.org/IService1/getPrescribedExercisesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Prescribe_Exercise[]> getPrescribedExercisesAsync(int studentNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllPrescribedExercises", ReplyAction="http://tempuri.org/IService1/getAllPrescribedExercisesResponse")]
        ServiceReference1.Prescribe_Exercise[] getAllPrescribedExercises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllPrescribedExercises", ReplyAction="http://tempuri.org/IService1/getAllPrescribedExercisesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Prescribe_Exercise[]> getAllPrescribedExercisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellor", ReplyAction="http://tempuri.org/IService1/GetCounsellorResponse")]
        ServiceReference1.Counsellor GetCounsellor(int Couns_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellor", ReplyAction="http://tempuri.org/IService1/GetCounsellorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Counsellor> GetCounsellorAsync(int Couns_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellors", ReplyAction="http://tempuri.org/IService1/GetCounsellorsResponse")]
        ServiceReference1.Counsellor[] GetCounsellors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellors", ReplyAction="http://tempuri.org/IService1/GetCounsellorsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Counsellor[]> GetCounsellorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        ServiceReference1.Student GetStudent(int Student_nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Student> GetStudentAsync(int Student_nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        ServiceReference1.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellorStudents", ReplyAction="http://tempuri.org/IService1/GetCounsellorStudentsResponse")]
        ServiceReference1.Student[] GetCounsellorStudents(int counsellorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCounsellorStudents", ReplyAction="http://tempuri.org/IService1/GetCounsellorStudentsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Student[]> GetCounsellorStudentsAsync(int counsellorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdmin", ReplyAction="http://tempuri.org/IService1/GetAdminResponse")]
        ServiceReference1.Admin GetAdmin(int Adminid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdmin", ReplyAction="http://tempuri.org/IService1/GetAdminResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Admin> GetAdminAsync(int Adminid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExercise", ReplyAction="http://tempuri.org/IService1/GetExerciseResponse")]
        ServiceReference1.Exercise GetExercise(int exerciseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExercise", ReplyAction="http://tempuri.org/IService1/GetExerciseResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Exercise> GetExerciseAsync(int exerciseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExercises", ReplyAction="http://tempuri.org/IService1/GetExercisesResponse")]
        ServiceReference1.Exercise[] GetExercises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExercises", ReplyAction="http://tempuri.org/IService1/GetExercisesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Exercise[]> GetExercisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBookings", ReplyAction="http://tempuri.org/IService1/getBookingsResponse")]
        ServiceReference1.Book_Consultation[] getBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBookings", ReplyAction="http://tempuri.org/IService1/getBookingsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getBookingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCounsBookings", ReplyAction="http://tempuri.org/IService1/getCounsBookingsResponse")]
        ServiceReference1.Book_Consultation[] getCounsBookings(int counsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCounsBookings", ReplyAction="http://tempuri.org/IService1/getCounsBookingsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getCounsBookingsAsync(int counsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStudentBookings", ReplyAction="http://tempuri.org/IService1/getStudentBookingsResponse")]
        ServiceReference1.Book_Consultation[] getStudentBookings(int studentnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStudentBookings", ReplyAction="http://tempuri.org/IService1/getStudentBookingsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getStudentBookingsAsync(int studentnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBooking", ReplyAction="http://tempuri.org/IService1/getBookingResponse")]
        ServiceReference1.Book_Consultation getBooking(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBooking", ReplyAction="http://tempuri.org/IService1/getBookingResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Book_Consultation> getBookingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/book_Consultation", ReplyAction="http://tempuri.org/IService1/book_ConsultationResponse")]
        bool book_Consultation(System.DateTime date, string time, int Stu_Num, int Couns_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/book_Consultation", ReplyAction="http://tempuri.org/IService1/book_ConsultationResponse")]
        System.Threading.Tasks.Task<bool> book_ConsultationAsync(System.DateTime date, string time, int Stu_Num, int Couns_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDiaryEntries", ReplyAction="http://tempuri.org/IService1/GetDiaryEntriesResponse")]
        ServiceReference1.Diary[] GetDiaryEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDiaryEntries", ReplyAction="http://tempuri.org/IService1/GetDiaryEntriesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Diary[]> GetDiaryEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentDiaryEntries", ReplyAction="http://tempuri.org/IService1/GetStudentDiaryEntriesResponse")]
        ServiceReference1.Diary[] GetStudentDiaryEntries(int studentnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentDiaryEntries", ReplyAction="http://tempuri.org/IService1/GetStudentDiaryEntriesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Diary[]> GetStudentDiaryEntriesAsync(int studentnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/logDiaryEntry", ReplyAction="http://tempuri.org/IService1/logDiaryEntryResponse")]
        bool logDiaryEntry(int stuNum, string title, string body, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/logDiaryEntry", ReplyAction="http://tempuri.org/IService1/logDiaryEntryResponse")]
        System.Threading.Tasks.Task<bool> logDiaryEntryAsync(int stuNum, string title, string body, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDiaryEntry", ReplyAction="http://tempuri.org/IService1/getDiaryEntryResponse")]
        ServiceReference1.Diary getDiaryEntry(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDiaryEntry", ReplyAction="http://tempuri.org/IService1/getDiaryEntryResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Diary> getDiaryEntryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditDiaryEntry", ReplyAction="http://tempuri.org/IService1/EditDiaryEntryResponse")]
        bool EditDiaryEntry(int id, string title, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditDiaryEntry", ReplyAction="http://tempuri.org/IService1/EditDiaryEntryResponse")]
        System.Threading.Tasks.Task<bool> EditDiaryEntryAsync(int id, string title, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/allocateSlot", ReplyAction="http://tempuri.org/IService1/allocateSlotResponse")]
        bool allocateSlot(int UserID, System.DateTime date, string timeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/allocateSlot", ReplyAction="http://tempuri.org/IService1/allocateSlotResponse")]
        System.Threading.Tasks.Task<bool> allocateSlotAsync(int UserID, System.DateTime date, string timeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deactivateSlot", ReplyAction="http://tempuri.org/IService1/deactivateSlotResponse")]
        bool deactivateSlot(int userID, System.DateTime date, string timeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deactivateSlot", ReplyAction="http://tempuri.org/IService1/deactivateSlotResponse")]
        System.Threading.Tasks.Task<bool> deactivateSlotAsync(int userID, System.DateTime date, string timeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getdayIDName", ReplyAction="http://tempuri.org/IService1/getdayIDNameResponse")]
        string getdayIDName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getdayIDName", ReplyAction="http://tempuri.org/IService1/getdayIDNameResponse")]
        System.Threading.Tasks.Task<string> getdayIDNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTimeIDByName", ReplyAction="http://tempuri.org/IService1/getTimeIDByNameResponse")]
        string getTimeIDByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTimeIDByName", ReplyAction="http://tempuri.org/IService1/getTimeIDByNameResponse")]
        System.Threading.Tasks.Task<string> getTimeIDByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLinkInfoByStudent", ReplyAction="http://tempuri.org/IService1/getLinkInfoByStudentResponse")]
        ServiceReference1.StuCounsLink getLinkInfoByStudent(int stunum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLinkInfoByStudent", ReplyAction="http://tempuri.org/IService1/getLinkInfoByStudentResponse")]
        System.Threading.Tasks.Task<ServiceReference1.StuCounsLink> getLinkInfoByStudentAsync(int stunum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMinCounsellor", ReplyAction="http://tempuri.org/IService1/getMinCounsellorResponse")]
        int getMinCounsellor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMinCounsellor", ReplyAction="http://tempuri.org/IService1/getMinCounsellorResponse")]
        System.Threading.Tasks.Task<int> getMinCounsellorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isSlotAvailable", ReplyAction="http://tempuri.org/IService1/isSlotAvailableResponse")]
        bool isSlotAvailable(System.DateTime date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isSlotAvailable", ReplyAction="http://tempuri.org/IService1/isSlotAvailableResponse")]
        System.Threading.Tasks.Task<bool> isSlotAvailableAsync(System.DateTime date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAvailableSlots", ReplyAction="http://tempuri.org/IService1/getAvailableSlotsResponse")]
        ServiceReference1.AvailableDateAndTime[] getAvailableSlots(int counsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAvailableSlots", ReplyAction="http://tempuri.org/IService1/getAvailableSlotsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AvailableDateAndTime[]> getAvailableSlotsAsync(int counsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LinkStudentToCounsellor", ReplyAction="http://tempuri.org/IService1/LinkStudentToCounsellorResponse")]
        bool LinkStudentToCounsellor(int studentID, int CounsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LinkStudentToCounsellor", ReplyAction="http://tempuri.org/IService1/LinkStudentToCounsellorResponse")]
        System.Threading.Tasks.Task<bool> LinkStudentToCounsellorAsync(int studentID, int CounsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnLinStudentFromCounsellork", ReplyAction="http://tempuri.org/IService1/UnLinStudentFromCounsellorkResponse")]
        bool UnLinStudentFromCounsellork(int studentID, int CounsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnLinStudentFromCounsellork", ReplyAction="http://tempuri.org/IService1/UnLinStudentFromCounsellorkResponse")]
        System.Threading.Tasks.Task<bool> UnLinStudentFromCounsellorkAsync(int studentID, int CounsID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.User loginUser(string username, string password)
        {
            return base.Channel.loginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.User> loginUserAsync(string username, string password)
        {
            return base.Channel.loginUserAsync(username, password);
        }
        
        public ServiceReference1.Student loginStudent(string username, string password)
        {
            return base.Channel.loginStudent(username, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Student> loginStudentAsync(string username, string password)
        {
            return base.Channel.loginStudentAsync(username, password);
        }
        
        public bool regUser()
        {
            return base.Channel.regUser();
        }
        
        public System.Threading.Tasks.Task<bool> regUserAsync()
        {
            return base.Channel.regUserAsync();
        }
        
        public bool EditStudent(int id, string name, string surname, string phonenumber, string email)
        {
            return base.Channel.EditStudent(id, name, surname, phonenumber, email);
        }
        
        public System.Threading.Tasks.Task<bool> EditStudentAsync(int id, string name, string surname, string phonenumber, string email)
        {
            return base.Channel.EditStudentAsync(id, name, surname, phonenumber, email);
        }
        
        public bool EditCounsellor(int id, string name, string surname, string phonenumber, string email)
        {
            return base.Channel.EditCounsellor(id, name, surname, phonenumber, email);
        }
        
        public System.Threading.Tasks.Task<bool> EditCounsellorAsync(int id, string name, string surname, string phonenumber, string email)
        {
            return base.Channel.EditCounsellorAsync(id, name, surname, phonenumber, email);
        }
        
        public bool ActivateCounsellor()
        {
            return base.Channel.ActivateCounsellor();
        }
        
        public System.Threading.Tasks.Task<bool> ActivateCounsellorAsync()
        {
            return base.Channel.ActivateCounsellorAsync();
        }
        
        public bool ActivateExercise()
        {
            return base.Channel.ActivateExercise();
        }
        
        public System.Threading.Tasks.Task<bool> ActivateExerciseAsync()
        {
            return base.Channel.ActivateExerciseAsync();
        }
        
        public bool addExercise(int id, string name, string description, char status, char active)
        {
            return base.Channel.addExercise(id, name, description, status, active);
        }
        
        public System.Threading.Tasks.Task<bool> addExerciseAsync(int id, string name, string description, char status, char active)
        {
            return base.Channel.addExerciseAsync(id, name, description, status, active);
        }
        
        public bool EditExercise(int id, string name, string decription, char status, char active)
        {
            return base.Channel.EditExercise(id, name, decription, status, active);
        }
        
        public System.Threading.Tasks.Task<bool> EditExerciseAsync(int id, string name, string decription, char status, char active)
        {
            return base.Channel.EditExerciseAsync(id, name, decription, status, active);
        }
        
        public bool prescribeExercise(int counsID, int studentID, int exerciseID, System.DateTime dateprescribed)
        {
            return base.Channel.prescribeExercise(counsID, studentID, exerciseID, dateprescribed);
        }
        
        public System.Threading.Tasks.Task<bool> prescribeExerciseAsync(int counsID, int studentID, int exerciseID, System.DateTime dateprescribed)
        {
            return base.Channel.prescribeExerciseAsync(counsID, studentID, exerciseID, dateprescribed);
        }
        
        public bool UnPrescribeExercise(int counsID, int exerciseID, int studentID)
        {
            return base.Channel.UnPrescribeExercise(counsID, exerciseID, studentID);
        }
        
        public System.Threading.Tasks.Task<bool> UnPrescribeExerciseAsync(int counsID, int exerciseID, int studentID)
        {
            return base.Channel.UnPrescribeExerciseAsync(counsID, exerciseID, studentID);
        }
        
        public bool exerciseCompleted(int counsID, int exerciseID, int studentID)
        {
            return base.Channel.exerciseCompleted(counsID, exerciseID, studentID);
        }
        
        public System.Threading.Tasks.Task<bool> exerciseCompletedAsync(int counsID, int exerciseID, int studentID)
        {
            return base.Channel.exerciseCompletedAsync(counsID, exerciseID, studentID);
        }
        
        public ServiceReference1.Prescribe_Exercise[] getPrescribedExercises(int studentNum)
        {
            return base.Channel.getPrescribedExercises(studentNum);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Prescribe_Exercise[]> getPrescribedExercisesAsync(int studentNum)
        {
            return base.Channel.getPrescribedExercisesAsync(studentNum);
        }
        
        public ServiceReference1.Prescribe_Exercise[] getAllPrescribedExercises()
        {
            return base.Channel.getAllPrescribedExercises();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Prescribe_Exercise[]> getAllPrescribedExercisesAsync()
        {
            return base.Channel.getAllPrescribedExercisesAsync();
        }
        
        public ServiceReference1.Counsellor GetCounsellor(int Couns_id)
        {
            return base.Channel.GetCounsellor(Couns_id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Counsellor> GetCounsellorAsync(int Couns_id)
        {
            return base.Channel.GetCounsellorAsync(Couns_id);
        }
        
        public ServiceReference1.Counsellor[] GetCounsellors()
        {
            return base.Channel.GetCounsellors();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Counsellor[]> GetCounsellorsAsync()
        {
            return base.Channel.GetCounsellorsAsync();
        }
        
        public ServiceReference1.Student GetStudent(int Student_nim)
        {
            return base.Channel.GetStudent(Student_nim);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Student> GetStudentAsync(int Student_nim)
        {
            return base.Channel.GetStudentAsync(Student_nim);
        }
        
        public ServiceReference1.Student[] GetStudents()
        {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Student[]> GetStudentsAsync()
        {
            return base.Channel.GetStudentsAsync();
        }
        
        public ServiceReference1.Student[] GetCounsellorStudents(int counsellorID)
        {
            return base.Channel.GetCounsellorStudents(counsellorID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Student[]> GetCounsellorStudentsAsync(int counsellorID)
        {
            return base.Channel.GetCounsellorStudentsAsync(counsellorID);
        }
        
        public ServiceReference1.Admin GetAdmin(int Adminid)
        {
            return base.Channel.GetAdmin(Adminid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Admin> GetAdminAsync(int Adminid)
        {
            return base.Channel.GetAdminAsync(Adminid);
        }
        
        public ServiceReference1.Exercise GetExercise(int exerciseid)
        {
            return base.Channel.GetExercise(exerciseid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Exercise> GetExerciseAsync(int exerciseid)
        {
            return base.Channel.GetExerciseAsync(exerciseid);
        }
        
        public ServiceReference1.Exercise[] GetExercises()
        {
            return base.Channel.GetExercises();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Exercise[]> GetExercisesAsync()
        {
            return base.Channel.GetExercisesAsync();
        }
        
        public ServiceReference1.Book_Consultation[] getBookings()
        {
            return base.Channel.getBookings();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getBookingsAsync()
        {
            return base.Channel.getBookingsAsync();
        }
        
        public ServiceReference1.Book_Consultation[] getCounsBookings(int counsID)
        {
            return base.Channel.getCounsBookings(counsID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getCounsBookingsAsync(int counsID)
        {
            return base.Channel.getCounsBookingsAsync(counsID);
        }
        
        public ServiceReference1.Book_Consultation[] getStudentBookings(int studentnum)
        {
            return base.Channel.getStudentBookings(studentnum);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Book_Consultation[]> getStudentBookingsAsync(int studentnum)
        {
            return base.Channel.getStudentBookingsAsync(studentnum);
        }
        
        public ServiceReference1.Book_Consultation getBooking(int id)
        {
            return base.Channel.getBooking(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Book_Consultation> getBookingAsync(int id)
        {
            return base.Channel.getBookingAsync(id);
        }
        
        public bool book_Consultation(System.DateTime date, string time, int Stu_Num, int Couns_id)
        {
            return base.Channel.book_Consultation(date, time, Stu_Num, Couns_id);
        }
        
        public System.Threading.Tasks.Task<bool> book_ConsultationAsync(System.DateTime date, string time, int Stu_Num, int Couns_id)
        {
            return base.Channel.book_ConsultationAsync(date, time, Stu_Num, Couns_id);
        }
        
        public ServiceReference1.Diary[] GetDiaryEntries()
        {
            return base.Channel.GetDiaryEntries();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Diary[]> GetDiaryEntriesAsync()
        {
            return base.Channel.GetDiaryEntriesAsync();
        }
        
        public ServiceReference1.Diary[] GetStudentDiaryEntries(int studentnum)
        {
            return base.Channel.GetStudentDiaryEntries(studentnum);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Diary[]> GetStudentDiaryEntriesAsync(int studentnum)
        {
            return base.Channel.GetStudentDiaryEntriesAsync(studentnum);
        }
        
        public bool logDiaryEntry(int stuNum, string title, string body, System.DateTime date)
        {
            return base.Channel.logDiaryEntry(stuNum, title, body, date);
        }
        
        public System.Threading.Tasks.Task<bool> logDiaryEntryAsync(int stuNum, string title, string body, System.DateTime date)
        {
            return base.Channel.logDiaryEntryAsync(stuNum, title, body, date);
        }
        
        public ServiceReference1.Diary getDiaryEntry(int id)
        {
            return base.Channel.getDiaryEntry(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Diary> getDiaryEntryAsync(int id)
        {
            return base.Channel.getDiaryEntryAsync(id);
        }
        
        public bool EditDiaryEntry(int id, string title, string description)
        {
            return base.Channel.EditDiaryEntry(id, title, description);
        }
        
        public System.Threading.Tasks.Task<bool> EditDiaryEntryAsync(int id, string title, string description)
        {
            return base.Channel.EditDiaryEntryAsync(id, title, description);
        }
        
        public bool allocateSlot(int UserID, System.DateTime date, string timeName)
        {
            return base.Channel.allocateSlot(UserID, date, timeName);
        }
        
        public System.Threading.Tasks.Task<bool> allocateSlotAsync(int UserID, System.DateTime date, string timeName)
        {
            return base.Channel.allocateSlotAsync(UserID, date, timeName);
        }
        
        public bool deactivateSlot(int userID, System.DateTime date, string timeName)
        {
            return base.Channel.deactivateSlot(userID, date, timeName);
        }
        
        public System.Threading.Tasks.Task<bool> deactivateSlotAsync(int userID, System.DateTime date, string timeName)
        {
            return base.Channel.deactivateSlotAsync(userID, date, timeName);
        }
        
        public string getdayIDName(string name)
        {
            return base.Channel.getdayIDName(name);
        }
        
        public System.Threading.Tasks.Task<string> getdayIDNameAsync(string name)
        {
            return base.Channel.getdayIDNameAsync(name);
        }
        
        public string getTimeIDByName(string name)
        {
            return base.Channel.getTimeIDByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getTimeIDByNameAsync(string name)
        {
            return base.Channel.getTimeIDByNameAsync(name);
        }
        
        public ServiceReference1.StuCounsLink getLinkInfoByStudent(int stunum)
        {
            return base.Channel.getLinkInfoByStudent(stunum);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StuCounsLink> getLinkInfoByStudentAsync(int stunum)
        {
            return base.Channel.getLinkInfoByStudentAsync(stunum);
        }
        
        public int getMinCounsellor()
        {
            return base.Channel.getMinCounsellor();
        }
        
        public System.Threading.Tasks.Task<int> getMinCounsellorAsync()
        {
            return base.Channel.getMinCounsellorAsync();
        }
        
        public bool isSlotAvailable(System.DateTime date, string time)
        {
            return base.Channel.isSlotAvailable(date, time);
        }
        
        public System.Threading.Tasks.Task<bool> isSlotAvailableAsync(System.DateTime date, string time)
        {
            return base.Channel.isSlotAvailableAsync(date, time);
        }
        
        public ServiceReference1.AvailableDateAndTime[] getAvailableSlots(int counsID)
        {
            return base.Channel.getAvailableSlots(counsID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AvailableDateAndTime[]> getAvailableSlotsAsync(int counsID)
        {
            return base.Channel.getAvailableSlotsAsync(counsID);
        }
        
        public bool LinkStudentToCounsellor(int studentID, int CounsID)
        {
            return base.Channel.LinkStudentToCounsellor(studentID, CounsID);
        }
        
        public System.Threading.Tasks.Task<bool> LinkStudentToCounsellorAsync(int studentID, int CounsID)
        {
            return base.Channel.LinkStudentToCounsellorAsync(studentID, CounsID);
        }
        
        public bool UnLinStudentFromCounsellork(int studentID, int CounsID)
        {
            return base.Channel.UnLinStudentFromCounsellork(studentID, CounsID);
        }
        
        public System.Threading.Tasks.Task<bool> UnLinStudentFromCounsellorkAsync(int studentID, int CounsID)
        {
            return base.Channel.UnLinStudentFromCounsellorkAsync(studentID, CounsID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.56.1/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
